const regionNames = document.querySelector('.regionSelect'),
      locationNames = document.querySelector('.locationSelect'),
      areaNames = document.querySelector('.areaSelect'),
      exploreBtn = document.querySelector('.explore-btn'),
      exBtn = document.querySelector('#exploreBtn'),
      pokeModel = document.querySelector('.poke-model'),
      pokeName = document.querySelector('.poke-name'),
      pokeStats = document.querySelector('.stats'),
      pokeBall = document.querySelector('.pokeball'),
      caughtCount = document.querySelector('#count'),
      caughtPoke = document.querySelector('.caught'),
      captureDiv = document.querySelector('#capture'),
      statsDiv = document.querySelector('#stats'),
      captureAudio = document.querySelector('#captureAudio'), 
      themeAudio = document.querySelector('#themeAudio'),
      encounterAudio = document.querySelector('#encounterAudio'),
      api = 'https://pokeapi.co/api/v2/region',
      pokemonApi = 'https://pokeapi.co/api/v2/pokemon',
      regions = [];


var locations = [],
    areas = [],
    pokemons = [],
    pokes = [],
    randomSprite,
    randomName,
    count = 0,
    selectedRegion;